# Usa la imagen base de Kali
FROM kalilinux/kali-rolling:latest
ENTRYPOINT ["/root/start-attacker.sh"]

# Instalar Interfaz Grafica
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes --no-install-recommends \
    #kali-desktop-xfce \
    xfce4 \
    xfce4-goodies \
    dbus-x11 \
    x11vnc \
    xvfb \
    xinit \
    xorg \
    sudo \
    novnc && \
    rm -rf /var/lib/apt/lists/*

# Actualiza el sistema e instala herramientas básicas
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes --no-install-recommends \
    openssh-server \
    git \
    nano \
    curl \
    wget \
    gedit \
    terminator \
    tmux \
    iputils-ping \
    firefox-esr \
    ffuf \
    pip \
    netcat-traditional \
    net-tools \
    proxychains \
    crowbar \
    nmap && \
    rm -rf /var/lib/apt/lists/*

# Configura el servicio SSH para permitir acceso remoto
RUN mkdir /var/run/sshd
RUN echo 'root:toor' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Configura VNC
COPY files/start-attacker.sh /root/start.sh
RUN chmod +x /root/start.sh
RUN mkdir -p ~/.vnc && x11vnc -storepasswd kali ~/.vnc/passwd

# Configurar Tools
RUN mkdir -p /root/Desktop/tools
WORKDIR /root/Desktop/tools
RUN echo "https://franc205.notion.site/Charla-Pivoting-f4101bdaa31b4dbca588907017c17634?pvs=4" >> notes.txt
COPY files/toolkit.tar.gz toolkit.tar.gz
RUN tar -xzvf toolkit.tar.gz
RUN wget https://raw.githubusercontent.com/3ndG4me/KaliLists/master/dirbuster/directory-list-2.3-medium.txt
WORKDIR /root

# Comando predeterminado para iniciar SSH y Bash
CMD ["/usr/sbin/sshd", "-D"]