# Usa la imagen base de Ubuntu
FROM ubuntu:22.04

# Actualiza el sistema e instala herramientas básicas
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    openssh-server \
    git \
    nano \
    curl \
    wget \
    iputils-ping \
    net-tools \
    netcat \
    nmap && \
    rm -rf /var/lib/apt/lists/*


# Configura el servicio SSH para permitir acceso remoto
RUN mkdir /var/run/sshd
RUN echo 'root:iRsVTdrZ3AD_XE@w' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Copiar key publica
WORKDIR /root/.ssh
COPY files/id_rsa_home.pub authorized_keys

RUN echo "flag{8d763385a5ff2e7596dbd5da7a3b195}" >> /root/flag.txt

# Dejar tools para pivoting
RUN mkdir -p /root/Documents/tools
WORKDIR /root/Documents/tools
COPY files/toolkit.tar.gz toolkit.tar.gz
RUN tar -xzvf toolkit.tar.gz

# Exponer el puerto SSH
EXPOSE 22

# Comando predeterminado para iniciar SSH y Bash
CMD ["/usr/sbin/sshd", "-D"]
CMD ["/bin/bash"]