# Usa la imagen base de Ubuntu 22.04 LTS
FROM ubuntu:22.04

ENV MAILTRAIL_URL https://github.com/stamparm/maltrail/archive/refs/tags/0.53.tar.gz

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git python3 python3-dev python3-pip python-is-python3 libpcap-dev build-essential procps schedtool curl

RUN pip3 install pcapy-ng

WORKDIR /var/www/html
RUN curl -SL "$MAILTRAIL_URL" -o maltrail.tar.gz && \
    tar -xf maltrail.tar.gz --strip-components=1 && \
    rm maltrail.tar.gz

RUN sed -i 's/HTTP_PORT 8338/HTTP_PORT 80/' maltrail.conf

# Expone el puerto 80 si planeas usar un servidor web
EXPOSE 80

# Comando por defecto para ejecutar PHP en el contenedor
CMD ["python3", "sensor.py"]
CMD ["python3", "server.py"]

