# Usa la imagen base de Ubuntu 22.04 LTS
FROM ubuntu:22.04
ENTRYPOINT ["/root/start-server51.sh"]

ENV MAILTRAIL_URL https://github.com/stamparm/maltrail/archive/refs/tags/0.53.tar.gz

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git \
    python3 \ 
    python3-dev \
    python3-pip \
    python-is-python3 \
    libpcap-dev build-essential \
    procps \
    schedtool \
    curl \
    wget \
    iputils-ping \
    net-tools \
    netcat \
    openssh-server && \
    rm -rf /var/lib/apt/lists/*

# Configura el servicio SSH para permitir acceso remoto
RUN mkdir /var/run/sshd
RUN echo 'root:efeA7U7@#Uf#KCTv' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN pip3 install pcapy-ng

WORKDIR /var/www/html
RUN curl -SL "$MAILTRAIL_URL" -o maltrail.tar.gz && \
    tar -xf maltrail.tar.gz --strip-components=1 && \
    rm maltrail.tar.gz

RUN sed -i 's/HTTP_PORT 8338/HTTP_PORT 80/' maltrail.conf

# Configura el entrypoint
COPY files/start-server51.sh /root/start.sh
RUN chmod +x /root/start.sh

RUN echo "flag{1a1dc91c907325c69271ddf0c944bc72}" >> /root/flag.txt

# Dejar tools para pivoting
RUN mkdir -p /root/Documents/tools
WORKDIR /root/Documents/tools
COPY files/toolkit.tar.gz toolkit.tar.gz
RUN tar -xzvf toolkit.tar.gz

# Expone el puerto 80 si planeas usar un servidor web
EXPOSE 80
EXPOSE 22

# Comando por defecto para ejecutar PHP en el contenedor
CMD ["python3", "sensor.py"]
CMD ["python3", "server.py"]

